# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(467, 278)
        mainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(5, 10, 251, 261))
        self.listWidget.setObjectName("listWidget")
        self.inptAltura = QtWidgets.QLineEdit(self.centralwidget)
        self.inptAltura.setGeometry(QtCore.QRect(360, 70, 81, 22))
        self.inptAltura.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inptAltura.setInputMask("")
        self.inptAltura.setText("")
        self.inptAltura.setReadOnly(False)
        self.inptAltura.setClearButtonEnabled(False)
        self.inptAltura.setObjectName("inptAltura")
        self.inptLargura = QtWidgets.QLineEdit(self.centralwidget)
        self.inptLargura.setGeometry(QtCore.QRect(270, 70, 81, 22))
        self.inptLargura.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inptLargura.setInputMask("")
        self.inptLargura.setText("")
        self.inptLargura.setReadOnly(False)
        self.inptLargura.setClearButtonEnabled(False)
        self.inptLargura.setObjectName("inptLargura")
        self.btnSaveRoot = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveRoot.setGeometry(QtCore.QRect(268, 99, 181, 21))
        self.btnSaveRoot.setObjectName("btnSaveRoot")
        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(270, 10, 171, 34))
        self.btn_open.setObjectName("btn_open")
        self.inptFileNamePlus = QtWidgets.QLineEdit(self.centralwidget)
        self.inptFileNamePlus.setGeometry(QtCore.QRect(270, 200, 181, 22))
        self.inptFileNamePlus.setObjectName("inptFileNamePlus")
        self.btn_redefinir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_redefinir.setGeometry(QtCore.QRect(270, 230, 181, 41))
        self.btn_redefinir.setObjectName("btn_redefinir")
        self.lblSaveRoot = QtWidgets.QLineEdit(self.centralwidget)
        self.lblSaveRoot.setGeometry(QtCore.QRect(270, 130, 181, 22))
        self.lblSaveRoot.setFrame(False)
        self.lblSaveRoot.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSaveRoot.setReadOnly(True)
        self.lblSaveRoot.setObjectName("lblSaveRoot")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 160, 191, 31))
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(270, 50, 121, 20))
        self.radioButton.setObjectName("radioButton")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Redimensionador"))
        self.inptAltura.setPlaceholderText(_translate("mainWindow", "Altura"))
        self.inptLargura.setPlaceholderText(_translate("mainWindow", "Largura"))
        self.btnSaveRoot.setText(_translate("mainWindow", "Definir pasta para salvar imagens"))
        self.btn_open.setText(_translate("mainWindow", "Abrir\n"
" Arquivos"))
        self.inptFileNamePlus.setPlaceholderText(_translate("mainWindow", "Extensão para o(s) arquivo(s) novos"))
        self.btn_redefinir.setText(_translate("mainWindow", "Salvar\n"
" Imagens"))
        self.label_2.setText(_translate("mainWindow", "Defina uma adição de nome para os \n"
"novos arquivos (Ex: \"_novo\")"))
        self.radioButton.setText(_translate("mainWindow", "Manter proporção"))
